jobs:
  build-macos:
    macos:
      xcode: 12.5.1
  build: 
    macos:
      xcode: 11.3.0 # indicate our selected version of Xcode
    steps: 
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/circleci-demo-macos.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app
workflows:
  version: 2
  test_build:
    jobs:
      - build-macos
      - build:
          requires:
            - test